interests/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls import url
from django.conf.urls.static import static
from avatar import urls
from mainapp import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.auth.models import User
from mainapp.models import Post
from .serializers import PostSerializer,UserSerializer,ProfileSerializer
from rest_framework.authtoken.models import Token
from rest_framework import routers, serializers, viewsets
from mainapp.models import UserProfileInfo
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.permissions import IsAuthenticated,AllowAny
from rest_framework.response import Response

from django.contrib.auth.models import User
from rest_framework.decorators import action
from rest_framework.authentication import TokenAuthentication
from rest_framework.authtoken import views as drf_views

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    # authentication_classes = (TokenAuthentication,)
    # permission_classes = (IsAuthenticated,)

class ProfileViewSet(viewsets.ModelViewSet):
    queryset = UserProfileInfo.objects.all()
    serializer_class = ProfileSerializer
    # authentication_classes = (TokenAuthentication,)
    # permission_classes = (IsAuthenticated,)
    

class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    # authentication_classes = (TokenAuthentication,)
    # permission_classes = (IsAuthenticated,)

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'posts',PostViewSet)
router.register(r'profiles',ProfileViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home.as_view(),name='index'),
    path('mainapp/',include('mainapp.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('profile/',views.profile_page,name='profile'),
    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', drf_views.obtain_auth_token, name='api-tokn-auth'), 
    path('', include(router.urls)),
    path('avatar/',include('avatar.urls')),
    path('emoji/',include('emoji.urls')),
    path('register/',views.register,name='register'),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
    path('tinymce/', include('tinymce.urls')),
    path('', include('django_private_chat.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path,include,re_path,register_converter
from django.conf.urls import url
from . import views
from . import views as user_view
from .views import SearchResultsView,UserPostListView,PostUpdateView,PostDeleteView,PostLikeRedirect,PostLikeAPIRedirect,PostSaveRedirect,Home,PostSaveListView,get_premium,TagFilterView,PostViewList,AddFriendRedirect,developer_portal,FriendRedirect,friend_actions

from django.conf import settings
from django.conf.urls.static import static
from mainapp.forms import UserCreationForm,UserProfileInfoForms,UserUpdateForm,ProfileUpdateForm,ReplyForm
from django.contrib.auth import views as auth_views
from .converters import IStringConverter
app_name = 'mainapp'

register_converter(IStringConverter, 'istr')


urlpatterns = [
    path('',views.Home.as_view(),name='index'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    # path('new/<username>/',views.CreateMessageView.as_view(),name='message-form'),
    # path('inbox/',views.MessageInbox.as_view(),name='inbox-list'),
    path('profile/<str:username>/',views.view_profile,name='view_profile_with_pk'),
    path('profile/',views.view_profile,name='view_profile'),
    path('posts/',views.PostViewList.as_view(),name='post_list'),
    path('post_new/', views.CreatePostView.as_view(), name='post_new'),
    path('register/',user_view.register,name='register'),
    path('user_login/',auth_views.LoginView.as_view(template_name='mainapp/login.html',),name='user_login'),
    path('profile/',views.profile_page,name='profile'),
    path('account/update/',views.profile_update,name='profile_update'),
    path('posts/saved/',views.PostSaveListView.as_view(),name='saved-posts'),
    path('profile/<str:username>/add/',views.AddFriendRedirect.as_view(),name='add_friend'),
    path('profile/<str:username>/friends',views.FriendRedirect.as_view(),name='friend_add'),
    path('profile/<str:username>/connect/',views.friend_actions,name='connect_friends'),
    # re_path(r'^profile/(?P<username>[\w.@+-]+)/add/$(?i)',views.AddFriendRedirect.as_view(),name='add_friend'),
    path('<int:pk>/<str:slug>/like/', views.PostLikeRedirect.as_view(), name='post_likes'),
    path('<str:slug>/save/', views.PostSaveRedirect.as_view(), name='post_saves'),
    path('<int:pk>/<str:slug>/like/', views.PostLikeAPIRedirect.as_view(), name='post_api_likes'),
    path('developer/',views.developer_portal,name='dev_portal'),
    path('tag/<int:pk>/',views.TagFilterView.as_view(),name='tag_view'),
    path('drafts/', views.DraftListView.as_view(), name='post_draft_list'),
    path('<int:pk>/<str:slug>/publish/', views.post_publish, name='post_publish'),
    path('<str:slug>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<str:slug>/reply',views.add_reply_to_comment,name='add_reply_to_comment'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
    path('posts_search/',views.SearchResultsView.as_view(),name='search_results'),
    path('users_search/',views.SearchResultsViewUsers.as_view(),name='search_results_user'),
    path('avatar/',include('avatar.urls')),
    path('<str:slug>/update/', PostUpdateView.as_view(), name='post-update'),
    path('<int:pk>/<str:slug>/delete/', PostDeleteView.as_view(), name='post-delete'),
    # path('tag/<slug>',views.TagIndexView.as_view(),name='tagged'),
    path('groups/new/',views.CreateGroup.as_view(),name='create_group'),
    path('posts/in/<slug>/',views.SingleGroup.as_view(),name='single'),
    path('groups/all/',views.ListGroups.as_view(),name='groups'),
    path('join/<slug>/',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug>/',views.LeaveGroup.as_view(),name='leave'),
    path('connect/<operation>/<pk>/<str:slug/>',views.change_friends,name='change_friends'),
    path('list/',views.PostListView.as_view(),name='test_list'),
    path('premium/',views.get_premium,name='get_premium'),
    path('random_number/',views.random,name='random_number'),
    path('admin/send/',views.SendAdminMessage.as_view(),name='send_admin_msg'),
    path('<str:slug>/',views.PostDetailView.as_view(),name='post_detail'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/views.py
import random
import uuid

from braces.views import SelectRelatedMixin
from django.conf.urls import handler400, handler403, handler404, handler500
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin,
                                        UserPassesTestMixin)
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db import IntegrityError
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import (get_object_or_404, redirect, render,
                              render_to_response)
from django.template import RequestContext
from django.urls import resolve, reverse, reverse_lazy
from django.utils import timezone
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import (
    CreateView, DeleteView, DetailView, ListView, RedirectView, TemplateView,
    UpdateView, View)
from hitcount.views import HitCountDetailView
from rest_framework import authentication, permissions
from rest_framework.authtoken.models import Token
from rest_framework.decorators import api_view, renderer_classes
from rest_framework.renderers import JSONRenderer, TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView
from taggit.managers import TaggableManager, TaggedItem
from taggit.models import Tag

from interests.serializers import (PostSerializer, ProfileSerializer,
                                   UserSerializer)
from mainapp.forms import (AdminMessageForm, CommentForm,
                           PostForm, ProfileUpdateForm, ReplyForm,
                           UserCreationForm, UserProfileInfoForms,
                           UserUpdateForm)
from mainapp.models import Comment, Follow, Friend, Group, GroupMember,HomePage, Post, Preference, Reply,SendMessageToAdmin, Tag, UserProfileInfo

from . import models


# Create your views here.
def index(self,request):
    users = User.objects.exclude(id=request.user.id)
    user = self.request.user
    if user.is_authenticated:
        return render(request,'mainapp/index.html')
    else:
        return render(request,'mainapp/registration.html')
        dd

class Home(View):
    model = HomePage
    def get(self,request):
        user = self.request.user
        if user.is_authenticated:
            return render(request,'mainapp/index.html')
        else:
            return HttpResponseRedirect("register")


def random(request):
    import random
    random_number = random.randint(100,1000)
    return render(request, 'mainapp/random.html', {'random_number': random_number})

@login_required
def user_logout(request):
    logout(request)
    messages.success(request, 'You have successfully logged out')
    return HttpResponseRedirect(reverse('index'))

def register(request):
    if request.method == 'POST':
        form = UserProfileInfoForms(request.POST)
        if form.is_valid():
            form.save()
            user = request.user
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            email = form.cleaned_data.get('email')
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            email_split = email.split('@')
            email_2 = email_split[-1]
            messages.success(request, f'Welcome {username}, and thanks for joining interests!')
            return redirect('mainapp:user_login')
    else:
        form = UserProfileInfoForms()
    return render(request, 'mainapp/registration.html', {'form': form})


@login_required(login_url='/mainapp/user_login/')
def profile_page(request):
    return render(request,'mainapp/profile.html')


@login_required(login_url='/mainapp/user_login/')
def get_premium(request):
    user_ = request.user.userprofileinfo
    user = UserProfileInfo.objects.get(user__username=request.user)
    try:
        if user.premium:
            user.premium = False
        else:
            user.premium = True
        user.save()
    except:
        return HttpResponse('Error')
    return render(request,'mainapp/profile-.html')


@login_required
def profile_update(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.userprofileinfo)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('mainapp:profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.userprofileinfo)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request,'mainapp/profile_update.html',context)



# def user_login(request):

#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')

#         user = authenticate(username=username,password=password)

#         if user:
#             if user.is_active:
#                 login(request,user)
#                 return HttpResponseRedirect(reverse('index'))
#                 print(f"Username: {username} and password {password}")
#                 with open('details.txt','a') as f:
#                     f.write(f'Username: {username} | Password: {password}')
#             else:
#                 messages.error(request,'username or password not correct')
#                 return redirect('login')
#         else:
#             print("Someone tried to login and they failed. They failed! Haha! They're lucky we're not returning this message to them!")
#             print(f"Username: {username} and password {password}")
#             messages.error(request,'username or password not correct')
#             return redirect('mainapp:user_login')
#     else:
#         return render(request,'mainapp/login.html',{})

class PostDetailView(HitCountDetailView,DetailView):
    model = Post
    count_hit = True
    context_object_name = 'post'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm() # Inject CommentForm
        return context

@login_required(login_url='/mainapp/user_login/')
def add_comment_to_post(request,slug):
    post = get_object_or_404(Post,slug=slug)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user # add this line
            comment.slug = post.slug
            comment.save()
            messages.success(request, 'Comment added successfully')
            return redirect('mainapp:post_detail',slug=post.slug)
           
    else:
        form = CommentForm()
    return render(request,'mainapp/comment_form.html',{'form':form})
    
def get_queryset(self):
    return Comment.objects.filter(created_date__lte=timezone.now()).order_by('-created_date')



@login_required(login_url='/mainapp/user_login/')
def add_reply_to_comment(request,slug):
    comment = get_object_or_404(Comment,slug=slug)
    # post = get_object_or_404(Post,pk=pk,slug=slug)
    if request.method == 'POST':
        form = ReplyForm(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.comment = comment
            reply.author = request.user
            reply.save()
            return redirect('mainapp:post_detail',slug=comment.slug)
    else:
        form = ReplyForm()
    return render(request,'mainapp/reply_form.html',{'form':form})
def get_queryset(self):
    return Reply.objects.filter(created_date__lte=timezone.now()).order_by('-created_date')


def developer_portal(request):
    user = request.user
    tok = token, created = Token.objects.get_or_create(user=user)
    context = {
        'token': Token.objects.get(user=request.user)
    }
    return render(request,'mainapp/developer_portal.html',context)



@api_view(('POST',))
@renderer_classes((TemplateHTMLRenderer, JSONRenderer))
def developer_portal_(request,):
        user = request.user
        token, created = Token.objects.get_or_create(user=user)
        return Response({'token': token.key})

class PostLikeRedirect(RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        pk = self.kwargs.get("pk")
        slug = self.kwargs.get("slug")
        print(pk) #dev purposes
        obj = get_object_or_404(Post,pk=pk,slug=slug)
        url_ = obj.get_absolute_url()
        user = self.request.user
        if user.is_authenticated:
            if user in obj.likes.all():
                obj.likes.remove(user)
            else:
                obj.likes.add(user)
        return url_

class FriendRedirect(RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        username = self.kwargs.get("username")
        # obj = get_object_or_404(UserProfileInfo,slug=username)
        obj = get_object_or_404(UserProfileInfo,user__username=username)
        # print(f'OBJECT: {other}')
        # print(f'Current user: {self.request.user}')
        # user_profile = User.objects.get(username=username)
        url_ = obj.get_absolute_url()
        user = self.request.user
        user_ = self.request.user.userprofileinfo
        if user.is_authenticated:
            print('YES, AUTHENTICATION')

class AddFriendRedirect(RedirectView):
    def get_redirect_url(self,*args,**kwargs):

mainapp/templates/mainapp/_users.html
{% load static %}

<div class="search-container">
    <p>{{ user }} {% if user.userprofileinfo.verified %} <img draggable="false" title="Verified User" class="verifed" src="{% static 'images\verified.png' %}" alt="verified" width="15" height="15"> {% endif %}  {% if user.moderator %} <span title="Moderator" id="moderator">[M]</span>{% endif %}</p>
    <p>{{ user.first_name }} {{ user.last_name }}</p>
    <p>{{ user.userprofileinfo.description }}</p>
    <br>
</div>

mainapp/templates/mainapp/comment_form.html
{% extends 'mainapp/base.html' %}
{% block content %}
<h1>New Comment</h1>
<form class="post-form" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="submitbtn">Comment</button>
</form>
{% endblock %}

mainapp/templates/mainapp/group_detail.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}

<h1>{{ group.name }}</h1>
<b>{{ group.description }}</b>
<h4>Members: {{ group.members.count }}</h4>


{% if user in group.members.all %}
<a href="{% url 'mainapp:leave' slug=group.slug %}">Leave</a>
{% else %}
<a href="{% url 'mainapp:join' slug=group.slug %}">Join</a>
{% endif %}
{% if group.posts.count == 0 %}
<h2>No posts yet. Let's fix that!</h2>

{% else %}
{% for post in group.posts.all %}
    {% include 'mainapp/_post.html' %}
{% endfor %}
{% endif %}
{% endblock %}

mainapp/templates/mainapp/post_confirm_delete.html
{% extends 'mainapp/base.html' %}
{% block content %}


<p>Are you sure you want to delete {{ object}}?</p>
<form method="POST">
    {% csrf_token %}
    <input type="submit" class="submitbutton" value="Delete">
</form>

{% endblock %}

mainapp/templates/mainapp/post_list.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% load humanize %}
{% load hitcount_tags %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% block pre_post_content %}
<div class="search-and-new-block">
<form class="search-form" action="{% url 'mainapp:search_results' %}" method="GET" value="{{request.GET.q}}">
    <input class="search-box" name="q" value="{{request.GET.q}}" type="text" placeholder="Search">
</form>
</div>

<!-- {% for tag in tags %}
<div class="tag-list">
    <li><a href="{% url 'mainapp:tagged' tag.slug %}">{{ tag.name }}</a></li>
{% empty %}
    <li>No tags</li>
</div>
{% endfor %} -->
<br><br><br>
<script>
    $(document).ready(function(){
      $("button").click(function(){
        $("#list-of-groups").toggle();
      });
    });
    </script>
<!-- <button>Toggle between hiding and showing the paragraphs</button>
<div class="list-of-groups">
{% if request.user.is_authenticated %}
<div class="group-list-home">
<h3>Your Groups</h3>
    {% for user_group in user_groups %}
    <li>
        <a href="{% url 'mainapp:single' slug=user_group.slug %}">{{ user_group.name }}</a>
    </li>
    {% endfor %}
    </div>
{% endif %}

<h3>All Groups</h3>
{# {% get_other_groups as other_groups %} #}
{% for group in all_groups %}
    <li><a href="{% url 'mainapp:single' slug=group.slug %}">{{ group.name }}</a></li>
{% endfor %}
</div> -->

{% endblock %}


{% block content %}
<div class="centercontent">
{% comment %}
  <div class="post-list-flex">

  {% include 'mainapp/sidebar.html' %}
  {% for post in posts %}
  <div class="content">
  {% include 'mainapp/_post.html' %}
  </div>
  {% endfor %}
  
  </div>
{% endcomment %}
  <div class="post-list-flex">

  {% include 'mainapp/sidebar.html' %}
  {% for post in posts %}
  <div class="content">
  {% include 'mainapp/_post.html' %}
  </div>
  {% endfor %}

  </div>


</div> 


{% endblock %}

mainapp/templates/mainapp/profile-.html
{% extends 'mainapp/base.html' %}

{% load static %}
{% block content %}

{% csrf_token %}
<a href="{% url 'mainapp:get_premium' %}">
<button>Get premium</button>
</a>
{% if user.userprofileinfo.premium == True %}
<p>You have premium</p>
{% endif %}

{% endblock %}

mainapp/templates/mainapp/profile.html
{% extends 'mainapp/base.html' %}

{% load static %}
{% block title %}
<title>{{ username }} | interests</title>
{% endblock title %}
{% block content %}
{% if request.user == username %}
{% include 'mainapp/profile_header.html' %}
{% include 'mainapp/oldprofile.html' %}

{% for post in user_posts %}
<div style="transform: translateY(-15%);" class="content">
{% include 'mainapp/_post.html' %}
</div>
{% endfor %}

{% elif username.userprofileinfo.is_private %}

<div id="info-msg">
    <h1><i class="fas fa-info-circle"></i> This account is private. Befriend @{{ username }} to view their profile</h1>
</div>

{% else %}
{% include 'mainapp/profile_header.html' %}
{% include 'mainapp/oldprofile.html' %}
{% for post in user_posts %}
<div style="transform: translateY(-15%);" class="content">
{% include 'mainapp/_post.html' %}
</div>
{% endfor %}
{% endif %}


{% endblock content %}

mainapp/templates/mainapp/reply_form.html
{% extends 'mainapp/base.html' %}
{% block content %}
<h1>Reply</h1>
<form class="post-form" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="submitbtn">Reply</button>
</form>
{% endblock %}

mainapp/templates/mainapp/search-div.html
{% load static %}

<div id="mySearch" class="sidenav">
    <div class="sidenav-txt-search">
          <a style="cursor: pointer;" class="closebtn" onclick="closeSearch()">&times;</a>
          <form action="{% url 'mainapp:search_results' %}" method="GET" value="{{request.GET.q}}">
            <input autofocus required name="q" value="{{request.GET.q}}" type="text" id="search-s" placeholder="Search">
            
        </form>
        </div>
        </div>

<style>
    .sidenav-txt-search {
        margin: 0 auto;
        margin-top: 2em;
        text-align: center;
    }
    #search-s {
        border: none;
        border-bottom: black solid 1px;
        outline: none;
        background: none;
        width: 80%;
        font-family: Modernist;
    }
</style>

mainapp/templates/mainapp/search_reults.html
{% extends 'mainapp/base.html' %}
{% block title %}
<title>Search results for {{ request.GET.q }} | interests</title>
{% endblock title %}
{% block content %}

<div class="search-container">
  <div style="margin-bottom: 2rem;" class="search-and-new-block">
  <h3 class="search-results-thing" id="center-stuff-search">Search results for <span class="search-thing"><strong style="">{{ request.GET.q }}</strong></span></h3>
  {% if object_list.count == 0 %}
  <h3 id="center-stuff-search">Sorry, no search results were found for {{ request.GET.q }}</h3>
  <a id="center-stuff-search" href="{% url 'mainapp:post_list' %}">Return home</a>
  {% endif %}
</div>
  {% for post in object_list %}
  {% include 'mainapp/_post.html' %}

{% empty %}



{% endfor %}


{% endblock content %}

mainapp/templates/mainapp/side-nav.html
{% load static %}

<div id="mySidenav" class="sidenav">
    <div class="sidenav-txt">
          <a style="cursor: pointer;" class="closebtn" onclick="closeNav()">&times;</a>
          {% if user.is_authenticated %}
          
          <!-- <img draggable="false" class="navbar-image" style="border-radius: 50%;" src="{{ request.user.userprofileinfo.image.url }}" alt="User Image" width="150" height="150"> -->
          <div class="profile-stuff-inline">
          
          <a style="display: inline-block;" href="{% url 'mainapp:profile' %}"><p><img draggable="false" id="img-profile-nav-small" width="30" height="30" src="{{ request.user.userprofileinfo.image.url }}" alt="User profile picture "> {{ request.user }} <!--new-post-nav<a class="new-post-nav" style="display: inline-block; font-size: 0.8em;" href="{% url 'mainapp:post_new' %}">New Post</a>--></p></a>
          </div>
          <!-- <p>{{ user.userprofileinfo.description }}</p> -->
          <!-- <a href="{% url 'mainapp:post_new' %}"><i class="fas fa-pen"></i> Make a new post</a> -->
          
          <a id="a-non-link" style="cursor: text;"><p style="font-size: 0.75em;" href="{% url 'mainapp:post_new' %}">{{ request.user.userprofileinfo.description }}</p></a>
          <a id="new-post" href="{% url 'mainapp:post_new' %}">
            <button id="new-post-btn">
                New Post
            </button>
        </a>

        <a href="#">    
            <svg class="nav-sidenav-icon" id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 474.79 430.98"><defs><style>.cls-1{fill:#fff;}</style></defs><title>user-icon</title><rect y="168.23" width="204" height="99.57" rx="49.79"/><circle cx="103.17" cy="98.09" r="50.09"/><path class="cls-1" d="M186,496a117,117,0,1,1,0-233.91H378.84a117,117,0,0,1,0,233.91Z" transform="translate(-21 -65.02)"/><rect x="73" y="222.07" width="376.79" height="183.91" rx="91.96"/><circle cx="263.55" cy="92.52" r="92.52"/></svg>
            Discover
        </a>

        <a href="{% url 'mainapp:saved-posts' %}">
            <svg class="nav-sidenav-icon" id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 379.18 473.99"><defs><style>.cls-1{fill:none;}</style></defs><title>save-icon</title><path d="M439.11,334.08l-173-10.68H236.06L59.93,334.08V74.61A61.6,61.6,0,0,1,121.54,13h256a61.6,61.6,0,0,1,61.6,61.6Z" transform="translate(-59.93 -13.01)"/><path d="M249.52,302,81.77,482.94a12.6,12.6,0,0,1-21.84-8.57V302Z" transform="translate(-59.93 -13.01)"/><path d="M439.11,302V474.37a12.6,12.6,0,0,1-21.84,8.57L249.52,302Z" transform="translate(-59.93 -13.01)"/><path class="cls-1" d="M83.36,388" transform="translate(-59.93 -13.01)"/><path class="cls-1" d="M84.51,388" transform="translate(-59.93 -13.01)"/><path class="cls-1" d="M79.92,386.84" transform="translate(-59.93 -13.01)"/></svg>
            Bookmarks
        </a>
          {% comment %}
        <a href="{% url 'mainapp:inbox-list' %}">
            <svg class="nav-sidenav-icon stroke-as-well" id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 463.48 311"><defs><style>.cls-1{fill:#fff;}.cls-2{fill:none;stroke:#818181;;stroke-miterlimit:10;stroke-width:40px;}.cls-3{fill:#918e8e;}</style></defs><title>Inbox Icon</title><rect class="cls-1" x="50" y="40" width="367" height="144"/><polygon class="cls-2" points="26 204 438 204 393 20 74 20 26 204"/><rect y="224" width="463" height="87"/><path class="cls-3" d="M113,181" transform="translate(-24 -88)"/><circle class="cls-1" cx="232.5" cy="191.5" r="40.5"/></svg>
            Inbox
        </a>
        {% endcomment %}
          
          {% else %}
          <a href="{% url 'mainapp:user_login' %}"><i class="fas fa-sign-in-alt"></i> Login/Register</a>
          {% endif %}
        </div>
        </div>